### ISSUE TITLE
Run Integrity Checker on a schedule

### ISSUE THREAD

**Issue by tyrann0us** [eriktorsner/integrity-checker#1]
Hi,
promising plugin!
I recently needed to switch from [Checksum Verifier](https://github.com/pluginkollektiv/checksum-verifier) which started to report a lot of false positives.
One thing I liked about this plugin was the ability to [run a daily check](https://github.com/pluginkollektiv/checksum-verifier/blob/master/inc/checksum_verifier.class.php#L277-L306). I would love to see this feature here as well. (I know you wrote about it in the [FAQ section](https://de.wordpress.org/plugins/integrity-checker/#faq-header).)
Any thoughts on this? Thanks!

**Comment by eriktorsner** [comment]
Hi tyrann0us, 

Sorry for not replying sooner, I wrote an answer when I first saw your issue, but I must have made a mistake when posting it.

There are a few options for scheduling available.

The easiest way is to upgrade to 0.10.0 of the plugin, it has monthly scheduling available for registered users and free scheduling for paid API subscribers. Sadly, sending alerts had to go from the 0.10 version, but it is a top priority for 0.11 that will be released asap.

If you prefer more freedom, you can check out the wp-cli version (https://github.com/eriktorsner/wp-checksum).

**Comment by tyrann0us** [comment]
Hi @eriktorsner,
thank you for getting back to me! I simply overlooked the options `Enable schedule scans` and `Scan frequency`. Maybe don't set an opacity on the first checkbox (for unregistered users) and show the scan frequency settings, but disabled?
I'm closing this. Thanks for the good work!
